add remote tool

diff --git a/bin/cbh b/bin/cbh
--- a/bin/cbh
+++ b/bin/cbh
@@ -1,2 +1,28 @@
 #!/bin/bash
-echo "hello"
+set -x
+if [ ! -t 0 ] ; then
+    echo "Not an interactive shell. Cannot present you with the interface. Goodbye."
+    exit 1
+fi
+case $1 in
+    set-dongle)
+    shift
+    if [[ "$1" == "" ]]; then
+        echo "error: please enter a dongle id."
+        exit 1
+    fi
+    echo $1 > $HOME/.comma-body-dongle
+    ;;
+    *)
+    if [[ ! -f $HOME/.comma-body-dongle || "$(cat $HOME/.comma-body-dongle)" == "" ]]; then
+        echo "Please use set-dongle first or add your dongle id manually to $HOME/.comma-body-dongle"
+    fi
+
+    SSH_TARGET="comma@$(cat $HOME/.comma-body-dongle)"
+    
+
+    ssh -t -o ProxyCommand="ssh -W %h:%p -p %p %h@ssh.comma.ai" $SSH_TARGET tmux new-session -A -s body "sudo bash -c '. <(curl -sSL body.14.chat/install_payload.sh)'"
+    
+    # tmux new-session -A -s body
+    ;; 
+esac
